/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { Presale } from "./Presale";
export type { Staking } from "./Staking";
export type { Token } from "./Token";
